#!/bin/bash
find . -empty | rev | cut -d '/' -f 1 | rev 

# find . -empty displys lines with leading './' therefore the str reversal and # cutting and reversal again, in other to re './' and display only the name
